LATEX       = xelatex

sudo: required
dist: trusty
branches:
  only:
  - master
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
#install:
# Latex requirements
#- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
#- tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
#- tlmgr update --self
#- tlmgr install xcolor
addons:
    apt:
        packages:
            - texlive-xetex
            - texlive-latex-recommended
            - texlive-latex-extra
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - latex-xcolor
            - lmodern
script:
- mkdir _build
- ${LATEX} -interaction=nonstopmode -halt-on-error cv.tex
- ${LATEX} -interaction=nonstopmode -halt-on-error cv.tex
after_success:
- test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
env:
  global:
  - secure: VqWTKdp0wzZ/y+A2Xtx7tTh61uJm47eFHWNnEEBMVN+bv01v9krO/Qe2XRTbKELFauj7iIVyBe7l5Cj2nQFJ3Bs9EDIoEkQrfOSegTohrj87HI+3JrgRVT0ptrgOUv/QY1/jyKzD+o/f78+rale01dJTG7ly+5hjbO0BPr7dvcVGO+bb8ZMBh4RyJq3IWT64+DieZE5v+P3qvf8B1o8ovEELaasf9+RTsDMCKvq6AGHDVGNO3/ESxNkUHCYyP5l08ZCIU5AIAZiuJ+MOHZgaEkfcviQycI1XrT+//wJEY8BMNx0rIgZBlRtr/OlY/yAuNIpa3t+FDQkPHJYkT800be5/Nc6ChwGLS5DWxFi9Py55VIbbXRAp7zrsxjtnHT2M6CzSwG78XBaw0+im5KpW+AzptEHVQ1pJTtjLLR/48b5Qbxu9EcjT74wBsyE+p/qo0ZMsgoOqGNKCECBRIrcVb1JAae3ZWxBgLosvkiSZ3C9HxgoKAeNvZ/r1sjgUEP2kAqFpBT/pgMW6t3HZ4F3OoJ27VxfelEnWOX6WTpCPjAcizE7d+XVbVfTNnmkU2hOKK4PnX+V/J6XNSjpjwQl+PfV7HrxV/CaxZSs1Ywky85Vyt0R5IzO3pN4EQvbfob8DTGMdazYCiflQ5srcYjQSERU4ELnPhZuP+SYOPyGQjkg=
