sudo: required
dist: trusty
branches:
  except:
  - pdf
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error cv.tex
- pdflatex -interaction=nonstopmode -halt-on-error cv.tex
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
env:
  global:
  - secure: IoX4fDvlXiiLI2F6s1o+OqJ53yt/uNZxcOLmyTWF4IEBMwbi5hc78tH8W1oB1MMAd7+oVaDl9b667MYRHBLu9OvSmz6QvIbJM5e33X4fZ6Y0Df98RxmjrxbKomtIV2Y/1Y/NcQzMuSsqi7UTj79iMnlj0mT3S+pMqHOtdrDaXDmigd4fXcJ26N9aIyJJBglqu4bXrFysaU1OeRmGpfkN5MLSPh2NcHwxV3/h9Z6urf6i99RLx6xxQr6w+HP+IopcWSk5hN7U6J10msTCSxK2Ao/jxAu7hsv5tHoawnYqD6fGlSWmJVbkCr9x60LXZ5990DHNfUhN/BU0usyHf65XlNxXlP0QlDq+EZVkv8xxC/mHV9SH9Phzjio0mfZHcfcKeewUo/0e1UMaTzylywhfM+O/kQI6qWDyVkqPwcvwTuXyDgBOK+DQx5/puzlV1SbQUSgrFlk1Yn1a/6lRegL8mN5wK1mZgVVKX7ueX1ZonYfQ8LBSXYiI/Sc8+JKxG8kaAsUJyrBpGOd3EqzThhr2cyNQ+J6OiE55B+tIO38+cIHCu9nl+gh23E8DdIIb1hHU9204WRGqYNb1A5H1GDbx9ylkgekNdDvyBHiRuCbOJjqJ5mQpsTZfMmaGZ0abIj7LGpiX21kEJU+4soBmoJlOvXeLcL1hGy1ZRyqpjN1n/DE=
